[package]
name = "test_crusty"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
crusty-core = {version = "~0.82.0", features=["select_rs"]}
